# Generated by Django 3.1.7 on 2021-03-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre Autor')),
                ('apellido', models.CharField(max_length=255, verbose_name='Apellido Autor')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook Autor')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter Autor')),
                ('isntagram', models.URLField(blank=True, null=True, verbose_name='Instagram Autor')),
                ('web', models.URLField(blank=True, null=True, verbose_name='Web Autor')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Autor')),
                ('estado', models.BooleanField(default=True, verbose_name='Autor activo/noActivo')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre categoria')),
                ('estado', models.BooleanField(default=True, verbose_name='Categoria activada/desactivada')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
